travis:
  secure:
    BINSTAR_TOKEN: fK4jvAzDP4gFzUAQ5PSODON6ZLE4fyrmfnbxzukZnSMXNf3Vc3XUnO6hawYu3/etPvIvIH0J0Ui3LjRC1NFb6fWIooUF9mp9Oza8GSj2Hp5bIDQ7XPehVzUQsRRFHgoGsuOnGy7NBjTNygVXk+H9tgu+Y0746IFD9rp3qcAeZhGrDv51p6ZqO+/VH4o0kwrKiICQFoANDsMj4T+ANmWQeIa8oNhXyPOiNj+AuZx7rWdJjFWbeV/r/ji/qa+91lNnZzZaIoHsWBQGCwfWs/i8msYr4AmyVBtbkTF071FWgBkRwxfqhRCSMXDMGvx6PaJgovyiy4voABrL63Z6nYbc0CKSoRsGoXX39Krw2Y/CS1nK8Y+Zmh6rTsSiC5uBXWf3ax0r72X6/0Qc/xPhroagBy+yn/hbLnhfRqQ9fj3NVgh+IIsIAllXavs81Vf3Kcih7yZ/A9VEwI9I20XDwnMOVtuWvZNt0FffIktyxT16NIJDJQXKo1IN6svJ0CxgFhPKNZ4Tj0ziMosy/gVbjUH90HMNDfUZM/0w9Yh06a9vVLXsyvs88Pxvr/7uo7eqXEMGBPWCltI+cJy7UE6PjDCclotoHxUztohOZ0K7HsA1BzRMKiFw1f0JIkY6p80PTMVRjOXJoTYYRl1pxf9xgHrOHHsD5y/Ff+kZDEOAY9xjCro=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
