travis:
  secure:
    BINSTAR_TOKEN: e+P0cRipD89YvpoVomBbaTjsD4H61oSpW3IIv5vlMTEJGtyqKRXfFtv/jcX4N1cN+MLg9xFlyAIS6lhzHz4omPWv3Hprn6V0QJIzTaUXCV/8GygPXT0bAORV6YhRjD2BWnhZ3QK8s9fpdzwcG6HcCO8UQiC78OooHU27UfQYOYsVa1uerI37+7rBZ76MEcb+LOW2SA6KsNLD3t5Uwd8O2F11sQdbHqWugOl5v1p2309aN7ZtBjOwAiJ4B5xqaB3/kj4Bi7b9ixIS/fs8RfL5JN6CFbiX6zVzPusb7nB22Zh3fwgG0J0AlDagUFAGHLHtbkTkNk1YThExaXfcee+d2nKR0ObPUUOSH/PEKFzKtSReTNs6IMO/v9JnxWq8RKao6cXiYX9qOji7lkrfWCi7iWbqpZwcqz/S80lQ0+8lL5svtqveesBuKJH55X+gQfrVtkN0z12TTB6bImWa/Opy6L4rQn7MJuy4eaHXaRe3/Kp7D/5CYN6x+ulTmXqrRW5awTZAaY5c74qZQTmEFFCA8P3yRyPSVSDIux/+O2+U5uFbkr1yTQFgZ01ZmnoTQZTZIKx/Hr+CjzlLvCioWefxwqX1EqfLpSwAD1KbreNnNk2Vm7Vj7Ch3FKPoKQvcnUbPPP065S1DsvC2Cbpfycy1tIWnH76NBVSH/JEGmMXm0dA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
